version: "3.9"
services:
  postgres:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "flute"
    volumes:
      - /var/www/flute-pgdata:/var/lib/postgresql/data:rw
    restart: always

  app:
    image: ghcr.io/flutengineering/backend:latest
    container_name: flut-backend-latest
    ports:
      - "8001:8001"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 8001
      DATABASE_URL: "postgres://postgres:postgres@postgres/flute"
    restart: unless-stopped
    command: "yarn start:docker"
    labels:
      - "com.centurylinklabs.watchtower.scope=flut-backend-latest"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope flut-backend-latest
    labels:
      - "com.centurylinklabs.watchtower.scope=flut-backend-latest"
